ORT=5000
NODE_ENV=development
CORS_ORIGIN=http://localhost:5173
SUPABASE_URL=https://ilabhvbuqhauamgehtuq.supabase.co
SUPABASE_SERVICE_KEY=sb_secret_LPfeJKnXY8u_AWbv181_Zw_kVRZkkw7
JWT_SECRET=supersecretjwtkey123
VITE_API_BASE_URL=http://localhost:5000/api

# AI Provider Keys
CEREBRAS_API_KEY=csk-wkr9wpc3ecp8ve2rkpr6kd8kcyydyfpmkxc2ypettrwk8ede
GEMINI_API_KEY=AIzaSyC8j27gdLqqp5kWzHGWZoOmLcSS-zWX3Ig
GROQ_API_KEY=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
